### ISSUE TITLE
[Maintenance]: blog.andreijiroh.dev will undergo maintenance due to Nest server migration

### ISSUE THREAD

**Issue by ajhalili2006** [andreijiroh-dev/infra-status#1]
### About this maintenance

The underlying [root server](https://docs.hetzner.com/robot/dedicated-server/general-information/root-server-upgrade) for [Hack Club Nest](https://hack.club/nest) where my Ghost publication is running will undergo a dedicated server upgrade/migration for improved reliability and additional capacity for new users, which may take up to a day or longer to complete.

### Is this a scheduled or emergency maintenance?

Routine maintenance

### Additional context

Taken from Hack Club Slack ([permalink](https://hackclub.slack.com/archives/C056WDR3MQR/p1725979666083549)):

> Hey `@birds`! Nest will be undergoing a [root server upgrade](https://docs.hetzner.com/robot/dedicated-server/general-information/root-server-upgrade) on **September 15, 2024, at 16:30 CEST / 10:30 AM EST / 7:30 AM PST / 8:00 PM IST / 2:30 PM GMT /** **[your timezone](https://time.cs50.io/20240915T0800+0530)**. We're upgrading to an [EX 101](https://www.hetzner.com/dedicated-rootserver/ex101/configurator/) server with 128 GB of DDR5 Non-ECC RAM. Since we’re going for an [upgrade without parallel operation and transferring all IPs from the existing server](https://docs.hetzner.com/robot/dedicated-server/general-information/root-server-upgrade#4-upgrade-without-parallel-operation-with-all-ips-transferred-from-the-existing-server), there will be significant downtime as we upgrade, transfer data, optimize configurations, and bring everything back online.
>
> We'll be shutting down the server approximately 12 hours earlier (around 04:30 CEST) to handle backups and prep work. We can’t provide an exact ETA, but we’re giving a maintenance window of 1-2 days. We appreciate your understanding and will keep you updated!
>
> - @cskartikey

**Comment by ajhalili2006** [comment]
Sorry for the ping, ~cskartikey! I am just adding the maintenance window for Nest into my infra status page's issue tracker to plan about manual backups and placing a temporary "under maintenance" page.

**Comment by cskartikey** [comment]
nw

**Comment by ajhalili2006** [comment]
**Update**: The maintenance is just started while I am doing a backup for `/var/lib/ghost/content` directory inside the container. (I have the database backup stored on Storj DCS, so we should be fine.) No DNS record change will happen to avoid potential issues once the maintenance is done.

More updates will be provided soon.

**Comment by ajhalili2006** [comment]
**Resolved**: We are so back since 09:48 PM (UTC), so I'll be updating the metadata and closing this one out.
